POST  http://localhost:3003/class
Content-Type: application/json

{
    "Class_Name":"shaw",
    "Initial_Date":"02/02/2022",
    "Final_Date":"12/06/2022",
    "Module":"5",
    "tipo": "integral"

}

 
###
POST http://localhost:3003/studentsnew
Content-Type: application/json

{
    "name": "Regiscleia",
    "birth_date":"13/05/1995",
    "email": "regiscleia@email.com",
    "class_id": 1
    
}

###
 GET http://localhost:3003/students?name=Regiscleia
 
 ###


###
POST http://localhost:3003/createteacher
Content-Type: application/json

{
    "name": "Gabriel",
    "birth_date":"11/03/1998",
    "email": "gabrielmina@email.com",
    "class_id": 1
}